######################################################################
# Automatically generated by qmake (3.0) Thu Jan 8 17:59:16 2015
######################################################################

QT+=testlib
TEMPLATE = app
TARGET = UnitTests
INCLUDEPATH += .

# Input
SOURCES += treetests.cpp \
   ../tree.h
