######################################################################
# Automatically generated by qmake (3.0) Thu Jan 8 17:59:16 2015
######################################################################

QT+=testlib

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = UnitTests
TEMPLATE = app

# Input
SOURCES += treetests.cpp \
   ../tree.h

INCLUDEPATH += .
