name: C/C++ CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Checkout Submodules
        run: git submodule sync --recursive && git submodule update --init --recursive

      - name: Update Software Repository
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update -qq

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install GCC 8
        run: |
          sudo apt-get install -qq g++-8
          sudo apt-get install -qq gcc-8
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 20
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8 20
          sudo update-alternatives --config gcc
          sudo update-alternatives --config g++
          sudo update-alternatives --config gcov
 
      - name: Install Conan
        run: pip install conan

      - name: Install OpenGL
        run: sudo apt-get install libgl-dev

      - name: Install Qt
        #uses: jurplel/install-qt-action@v1
        run: |
          sudo apt-get install -y python3-setuptools
          pip3 install cuteci
          cuteci \
              --rm \
              --installer http://download.qt.io/official_releases/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run \
              install \
              --verbose \
              --destdir ~/Qt \
              --packages qt.qt5.5130.gcc_644,qt.tools
      
      - name: Set Environment Variables
        run: |
          export QT_DEBUG_PLUGINS=1
          echo ${PATH}

      - name: Download Conan Packages
        run: |
            cd ${GITHUB_WORKSPACE}
            mkdir Conan && cd Conan
            conan install ..
            cd ${GITHUB_WORKSPACE}

      - name: Build D-Viz
        run: |
          ~/Qt/5.13.0/gcc_64/bin/qmake CONFIG+=debug D-Viz.pro
          make

      - name: Run Tests
        run: |
          cd ${GITHUB_WORKSPACE}/Output/Debug
          ./UnitTests
